site_name: steam

repo_name: "2021.2-steam"
repo_url: "https://github.com/Requisitos-de-Software/2021.2-steam"

theme:
  name: material
  language: "pt"
  logo: "assets/steam-logo.svg"
  favicon: "assets/steam-logo.svg"
  palette:
    scheme: default
    primary: "blue grey"
    accent: "indigo"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/style.css

nav:
  - Início: index.md
  - Planejamento:
      - Metodologia: planejamento/metodologia.md
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
  - Pré-rastreabilidade:
      - RichPictures: pre_rastreabilidade/rich_pictures.md
  - Elicitação:
      - Personas: elicitacao/personas.md
      - Técnicas:
          - Brainstorming: elicitacao/tecnicas/brainstorm.md
          - Observação: elicitacao/tecnicas/observacao.md
          - Introspecção: elicitacao/tecnicas/introspeccao.md
          - Questionário: elicitacao/tecnicas/questionario.md
      - Priorização:
          - MoSCoW: elicitacao/priorizacao/MoSCoW.md
      - Resultado: elicitacao/resultado.md
  - Modelagem:
      - Especificação Suplementar: modelagem/especificacao_suplementar.md
      - Cenários: modelagem/cenarios.md
      - Casos de uso: modelagem/casos_de_uso.md
      - Lêxicos: modelagem/lexicos.md
      - NFR Framework: modelagem/nfr_framework.md
      - Backlog:
          - Backlog do produto: modelagem/backlog/backlog_produto.md
          - EP01 - Conta: modelagem/backlog/ep01_conta.md
          - EP02 - Perfil: modelagem/backlog/ep02_perfil.md
          - EP03 - Social: modelagem/backlog/ep03_social.md
          - EP04 - Suporte: modelagem/backlog/ep04_suporte.md
  - Analise:
    - Verificação:
      - Verificação: analise/verificacao/verificacao.md
      - Backlog: analise/verificacao/backlog.md
      - Casos de uso: analise/verificacao/casos_de_uso.md
      - Cenários: analise/verificacao/cenarios.md
      - Léxicos: analise/verificacao/lexicos.md
      - NFR framework: analise/verificacao/nfr_framework.md
      - Rich Pictures: analise/verificacao/rich_picture.md
    - Validação: 
      - Comprovação Informal: analise/validacao/comprovacao_informal.md
  - Pós-rastreabilidade:
    - Foward-from: pos_rastreabilidade/foward_from.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentação 4: apresentacoes/apresentacao4.md

dev_addr: "0.0.0.0:8000"
